### ISSUE TITLE
Allow changing API URL for fault injection testing

### ISSUE THREAD

**Issue by adamzr** [GideonLeGrange/haveibeenpwned#3]
Can you make it possible to change the URL for Have I Been Pwned in the client library for testing purposes? I want to be able to switch it to a proxy server, so I can test what happens if the server goes down or times out. Thanks!

**Comment by GideonLeGrange** [comment]
I implemented this. Please se #4 for details.

**Comment by adamzr** [comment]
That was fast! Thanks @GideonLeGrange ! I'll wait for the artifact to go through and then try it. Really appreciate it!
