### ISSUE TITLE
HaveIBeenPwndApi Adaptation for Android ?

### ISSUE THREAD

**Issue by eakteam** [GideonLeGrange/haveibeenpwned#6]
It would be awesome if you adapt this library to support Android 16+ 
`Optional` classes and `java.util.stream` are supported from Android API level 24+ , can you make an workaround to support older versions too ?

Thanks for the good work

**Comment by GideonLeGrange** [comment]
@eakteam Thank you for the suggestion. 

Unfortunately I cannot spend time making this project backwards compatible to that extent. Android 4.1 (API 16) is 8 years old, and Android 7 (API 24) is already 4 years old. 

Java 1.8 which introduced `Optional` and `Stream` is 6 years old and having this project 1.8 compatible seems fair.

If you really need this, you can fork the project and modify the source code, it should be mostly in one or two places.
